tsdb_rw:
 image: utcn/tcollector
 container_name: prod_tcollector
 hostname: tcollector_1
 volumes:
 - ./data/dump:/opt/data/dump
 - ./data/ssh/keys:/etc/ssh/keys
 external_links:
 - prod_tsdb_rw:tsdb

